CREATE SCHEMA IF NOT EXISTS SECURITY;

CREATE TABLE SECURITY.USERS(
  ID SERIAL NOT NULL,
  LOGIN VARCHAR NOT NULL,
  PASSWORD VARCHAR NOT NULL,
  CONSTRAINT USERS_PK PRIMARY KEY (ID)
);

CREATE TABLE SECURITY.ROLES(
  ID SERIAL NOT NULL,
  ROLE VARCHAR NOT NULL,
  UNIQUE(ROLE),
  CONSTRAINT ROLES_PK PRIMARY KEY (ID)
);

CREATE TABLE SECURITY.USER_ROLES(
  USER_ID INT NOT NULL REFERENCES SECURITY.USERS(ID) ON UPDATE CASCADE ON DELETE CASCADE,
  ROLE_ID INT NOT NULL REFERENCES SECURITY.ROLES(ID) ON UPDATE CASCADE ON DELETE CASCADE
);