INSERT INTO COMPANY (NAME)
VALUES
('compA'),
('compB'),
('compC');

INSERT INTO PRODUCT (NAME)
VALUES
('Keks'),
('Ukrop');

INSERT INTO CREATED_PRODUCTS (COMPANY_ID, PRODUCT_ID, COUNT, DATE)
VALUES
(1, 1, 13, '20211203'),
(2, 2, 13, '20211203');
