CREATE TABLE COMPANY(
  ID SERIAL NOT NULL,
  NAME VARCHAR NOT NULL,
  INDIVIDUAL_TAX_NUMBER VARCHAR NOT NULL,
  COMPANY_CHECK VARCHAR NOT NULL,
  CONSTRAINT COMPANY_PK PRIMARY KEY (ID)
);

CREATE TABLE WAYBILL(
  ID SERIAL NOT NULL,
  DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  COMPANY_ID INT NOT NULL REFERENCES COMPANY(id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT WAYBILL_PK PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT(
  ID SERIAL NOT NULL,
  NAME VARCHAR NOT NULL,
  INNER_CODE VARCHAR NOT NULL,
  CONSTRAINT PRODUCT_PK PRIMARY KEY (ID)
);

CREATE TABLE WAYBILL_PRODUCTS(
  ID SERIAL NOT NULL,
  WAYBILL_ID INT NOT NULL REFERENCES WAYBILL(id) ON UPDATE CASCADE ON DELETE CASCADE,
  PRODUCT_ID INT NOT NULL REFERENCES PRODUCT(id) ON UPDATE CASCADE ON DELETE CASCADE,
  PRICE INT NOT NULL,
  COUNT INT NOT NULL,
  CONSTRAINT WAYBILL_PRODUCTS_PK PRIMARY KEY (ID)
);